version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/dotnet/Dockerfile
  app:
    build:
      context: .
      dockerfile: ./Docker/vuejs/Dockerfile
  mssql:
    image: 'microsoft/mssql-server-linux'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret@123
    volumes:
        - './drive:/var/opt/mssql'